import { PregnancyPhaseInfo } from '../types';

export const WEEKLY_DATA: Record<number, PregnancyPhaseInfo> = {
  4: {
    week: 4,
    trimester: 1,
    month: 1,
    babySize: '2mm',
    babyComparison: 'Semente de Papoula',
    babyComparisonIcon: '🌱',
    babyDevelopment: 'O embrião está se fixando no útero. As células começam a se especializar.',
    motherChanges: 'Atraso menstrual. Você pode sentir cansaço e seios sensíveis.',
    commonSymptoms: ['Cansaço', 'Seios sensíveis', 'Leve cólica'],
    alerts: ['Sangramento intenso', 'Dores fortes'],
    nextStep: 'Agendar primeira consulta de pré-natal.',
    importantExam: 'Teste de farmácia ou Beta HCG.',
    observeNow: 'Alimentação saudável e início do ácido fólico.',
    energyLevel: 'Baixa - O corpo está trabalhando muito.',
    moodChanges: 'Ansiedade e euforia.',
    cravings: 'Ainda sem desejos específicos.',
  },
  8: {
    week: 8,
    trimester: 1,
    month: 2,
    babySize: '1.6cm',
    babyComparison: 'Framboesa',
    babyComparisonIcon: '🍓',
    babyDevelopment: 'O coração bate forte. Braços e pernas começam a se formar.',
    motherChanges: 'O útero está crescendo. Enjoos matinais podem ser intensos.',
    commonSymptoms: ['Enjoo', 'Vômito', 'Frequência urinária'],
    alerts: ['Vômitos incontroláveis', 'Desidratação'],
    nextStep: 'Primeiro ultrassom para ouvir o coração.',
    importantExam: 'Ultrassom transvaginal.',
    observeNow: 'Hidratação constante.',
    energyLevel: 'Muito Baixa - Pico de progesterona.',
    moodChanges: 'Irritabilidade e sensibilidade.',
    cravings: 'Aversão a cheiros fortes.',
  },
  12: {
    week: 12,
    trimester: 1,
    month: 3,
    babySize: '5.4cm',
    babyComparison: 'Ameixa',
    babyComparisonIcon: '🍑',
    babyDevelopment: 'O bebê já se mexe, embora você não sinta. Os órgãos estão formados.',
    motherChanges: 'O risco de aborto diminui drasticamente. A barriga começa a aparecer.',
    commonSymptoms: ['Tontura', 'Dores de cabeça', 'Melhora do enjoo'],
    alerts: ['Dores de cabeça persistentes'],
    nextStep: 'Exame de Translucência Nucal.',
    importantExam: 'Ultrassom Morfológico do 1º Trimestre.',
    observeNow: 'Uso de hidratantes para evitar estrias.',
    energyLevel: 'Melhorando gradualmente.',
    moodChanges: 'Mais estabilidade emocional.',
    cravings: 'Desejo por frutas cítricas.',
  },
  16: {
    week: 16,
    trimester: 2,
    month: 4,
    babySize: '11.6cm',
    babyComparison: 'Abacate',
    babyComparisonIcon: '🥑',
    babyDevelopment: 'O bebê consegue segurar o cordão umbilical. O sistema circulatório funciona.',
    motherChanges: 'Fase da "brilho da gravidez". Mais energia e libido.',
    commonSymptoms: ['Nariz entupido', 'Crescimento de cabelos e unhas'],
    alerts: ['Pressão alta'],
    nextStep: 'Planejar o enxoval.',
    importantExam: 'Exames de sangue de rotina.',
    observeNow: 'Postura ao sentar e dormir.',
    energyLevel: 'Alta - O melhor momento da gestação.',
    moodChanges: 'Sentimento de conexão com o bebê.',
    cravings: 'Desejos por doces ou combinações estranhas.',
  },
  20: {
    week: 20,
    trimester: 2,
    month: 5,
    babySize: '16.4cm',
    babyComparison: 'Banana',
    babyComparisonIcon: '🍌',
    babyDevelopment: 'Metade do caminho! O bebê já ouve sons externos.',
    motherChanges: 'O umbigo pode começar a saltar. Você sente os primeiros chutes.',
    commonSymptoms: ['Chutes do bebê', 'Cãibras nas pernas'],
    alerts: ['Inchaço repentino nas mãos e rosto'],
    nextStep: 'Ultrassom Morfológico do 2º Trimestre.',
    importantExam: 'Morfológico de 2º Trimestre.',
    observeNow: 'Conversar e colocar música para o bebê.',
    energyLevel: 'Boa, mas cansaço ao caminhar muito.',
    moodChanges: 'Ansiedade pelo ultrassom morfológico.',
    cravings: 'Desejo por alimentos salgados.',
  },
  24: {
    week: 24,
    trimester: 2,
    month: 6,
    babySize: '30cm',
    babyComparison: 'Milho',
    babyComparisonIcon: '🌽',
    babyDevelopment: 'O bebê está ganhando peso e gordura. Os pulmões se desenvolvem.',
    motherChanges: 'Aparecimento da linha nigra. Possível azia.',
    commonSymptoms: ['Azia', 'Prisão de ventre', 'Olhos secos'],
    alerts: ['Contrações rítmicas'],
    nextStep: 'Teste de glicose (diabetes gestacional).',
    importantExam: 'Curva Glicêmica.',
    observeNow: 'Consumo de fibras e água.',
    energyLevel: 'Moderada.',
    moodChanges: 'Preocupação com o parto.',
    cravings: 'Desejo por gelo ou coisas geladas.',
  },
  28: {
    week: 28,
    trimester: 3,
    month: 7,
    babySize: '37.6cm',
    babyComparison: 'Berinjela',
    babyComparisonIcon: '🍆',
    babyDevelopment: 'O bebê abre os olhos e tem cílios. O cérebro está muito ativo.',
    motherChanges: 'Dificuldade para achar posição para dormir. Falta de ar leve.',
    commonSymptoms: ['Dor nas costas', 'Insônia', 'Sonhos vívidos'],
    alerts: ['Diminuição brusca dos movimentos fetais'],
    nextStep: 'Vacinas do terceiro trimestre (DTPA).',
    importantExam: 'Vacinação e exames de 3º trimestre.',
    observeNow: 'Contagem de movimentos do bebê.',
    energyLevel: 'Baixa - O peso da barriga incomoda.',
    moodChanges: 'Instabilidade emocional volta um pouco.',
    cravings: 'Desejo por carboidratos.',
  },
  32: {
    week: 32,
    trimester: 3,
    month: 8,
    babySize: '42.4cm',
    babyComparison: 'Abóbora',
    babyComparisonIcon: '🎃',
    babyDevelopment: 'O bebê está praticando a respiração e a deglutição.',
    motherChanges: 'Contrações de Braxton Hicks (treinamento).',
    commonSymptoms: ['Contrações de treinamento', 'Vontade frequente de urinar'],
    alerts: ['Perda de líquido amniótico'],
    nextStep: 'Preparar a mala da maternidade.',
    importantExam: 'Ultrassom com Doppler.',
    observeNow: 'Sinais de parto prematuro.',
    energyLevel: 'Muito Baixa.',
    moodChanges: 'Instinto de "ninho" (querer arrumar tudo).',
    cravings: 'Refeições menores e mais frequentes.',
  },
  36: {
    week: 36,
    trimester: 3,
    month: 9,
    babySize: '47.4cm',
    babyComparison: 'Melancia',
    babyComparisonIcon: '🍉',
    babyDevelopment: 'O bebê está quase pronto. A maioria já está de cabeça para baixo.',
    motherChanges: 'A barriga "baixa" quando o bebê encaixa na pelve.',
    commonSymptoms: ['Pressão pélvica', 'Inchaço nos pés'],
    alerts: ['Pressão alta', 'Visão embaçada'],
    nextStep: 'Exame de Estreptococo B.',
    importantExam: 'Cultura de Estreptococo.',
    observeNow: 'Instalação da cadeirinha no carro.',
    energyLevel: 'Exaustão.',
    moodChanges: 'Ansiedade extrema e impaciência.',
    cravings: 'Alimentos leves para evitar azia.',
  },
  40: {
    week: 40,
    trimester: 3,
    month: 9,
    babySize: '51.2cm',
    babyComparison: 'Abóbora Gigante',
    babyComparisonIcon: '🎃',
    babyDevelopment: 'Desenvolvimento completo. Pronto para conhecer o mundo!',
    motherChanges: 'O colo do útero começa a dilatar e afinar.',
    commonSymptoms: ['Perda do tampão mucoso', 'Contrações reais'],
    alerts: ['Bolsa rompida', 'Contrações a cada 5 minutos'],
    nextStep: 'Monitoramento fetal frequente.',
    importantExam: 'Cardiotocografia.',
    observeNow: 'Sinais de trabalho de parto.',
    energyLevel: 'Mínima.',
    moodChanges: 'Foco total no nascimento.',
    cravings: 'Desejo que o bebê nasça logo!',
  },
};

export const getPhaseInfo = (week: number): PregnancyPhaseInfo => {
  const weeks = Object.keys(WEEKLY_DATA).map(Number).sort((a, b) => a - b);
  let closestWeek = weeks[0];
  for (const w of weeks) {
    if (week >= w) {
      closestWeek = w;
    } else {
      break;
    }
  }
  return { ...WEEKLY_DATA[closestWeek], week };
};
